### ISSUE TITLE
on kidney stone detection project gui based

### ISSUE THREAD

**Issue by kirtivardhan80** [junaid-1013/Kidney-Stone-Detection#1]
i have seen your project its very good can you provide a flowchart of the project

**Comment by junaid-1013** [comment]
thanks you for the feedback
yes sure I will do that

**Comment by kirtivardhan80** [comment]
> thanks you for the feedback
> yes sure I will do that 

Thanku and can you tell me that without connecting svm model to gui how is it working

**Comment by junaid-1013** [comment]
the cell of the GUI is placed before SVM but it should run after the SVM model is trained
I am updating the file so that it is easy to understand how the code is working

**Comment by junaid-1013** [comment]
I was busy with some other projects that's why I don't get time to respond to you I am currently working on it it will be updated in few minutes

**Comment by junaid-1013** [comment]
The code is updated now you can view if you still have nay questions please ask I will respond it asap.

Work Flow is like this
1. CNN
2. Hog features Extractions
3. SVM
4. GUI

**Comment by kirtivardhan80** [comment]
Thanku much appreciated

**Comment by junaid-1013** [comment]
For a detailed project overview and comprehensive explanation, please refer to my latest commit. Additionally, please review the code changes I have made, including the new GUI feature.

**Comment by kirtivardhan80** [comment]
Thanks, I'll take a look.

**Comment by JuGit-pk** [comment]
Well done
